### ISSUE TITLE
Error using mandrake

### ISSUE THREAD

**Issue by OrsonMM** [bacpop/mandrake#39]
Hi mandrake team 

I am new using mandrake, I use these commands but send error

> mandrake --sketches database.h5 --labels metadata_mandrake.tsv --kNN 80 --perplexity 15 --maxIter 10000 --cpus 20 --seed 12465

error 

![image](https://user-images.githubusercontent.com/12600107/232184733-12b0ac22-40a9-46bd-a5ac-86203d86ad3a.png)

I think so that is problem with file input for parameter --labels. It looks like 

![image](https://user-images.githubusercontent.com/12600107/232184798-cca3ed71-39dd-44fb-93ff-b48acb8db239.png)

I tried without ' in the manes but is the same error. 

Please help me.

**Comment by johnlees** [comment]
From the [docs](https://mandrake.readthedocs.io/en/latest/input.html#input-options):

> Any of the following modes also accept --labels, which give the categories to colours points by in the output plots. This should be a tab-separated file with no header, the first column containing sample names, and the second column containing the labels for each sample.

It looks like this file is isformatted. Remove the header, quotes and use tabs not commas e.g.
```
FS01851358	32
FS01851362	32
```

**Comment by johnlees** [comment]
And see the example in `test/`: https://github.com/bacpop/mandrake/blob/master/test/data/labels.txt

**Comment by OrsonMM** [comment]
It workrs, thank you.  :)

Number of workers less than number of available threads, increasing n_workers automatically
Calculating distances
Calculating distances using 20 thread(s)
Progress (CPU): 28.2%
Progress (CPU): 41.0%
Progress (CPU): 58.2%

Progress (CPU): 78.7%
Progress (CPU): 78.8%

Progress (CPU): 100.0%
Running SCE
Running on CPU
Preprocessing 9831 samples with perplexity = 15 took 29ms
Optimizing       Progress: 99.8%, eta=0.0020, Eq=0.9999999918, clashes=0.4%
Optimizing done in 0s
Drawing plots
